name:                homeMade
version:             0.1.0.0
github:              "githubuser/homeMade"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/homeMade#readme>

dependencies:
- base >= 4.7 && < 5
- attoparsec >= 0.13.2.3
- text >= 1.2.3.1
- containers >= 0.6.0.1
- hspec >= 2.7.1

library:
  source-dirs: src

executables:
  homeMade-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homeMade

tests:
  homeMade-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - homeMade
